package Environments::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Environments::Schema',
    #DTE2=(DESCRIPTION=(ENABLE=BROKEN)(LOAD_BALANCE=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=165.184.34.104)(PORT=1522))(ADDRESS=(PROTOCOL=TCP)(HOST=165.184.34.105)
    #(PORT=1522))(ADDRESS=(PROTOCOL=TCP)(HOST=165.184.34.106)(PORT=1522))(CONNECT_DATA=(SERVICE_NAME=DTE2)))
    connect_info => {
       #"dbi:Oracle:HOST=165.184.34.104;port=1522"
        dsn => 'dbi:Oracle:host=165.184.34.104;service_name=DTE2;port=1522',
        user => 'ENV_MGT',
        password => 'envown123',
    }
);

=head1 NAME

Environments::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Environments>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Environments::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.25

=head1 AUTHOR

James Sandlin,James Sandlin,512-873-6637,James.Sandlin@hhsc.state.tx.us,HHSC,CR52960

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
